---
change_number:
  - CHG123456
add:
  1:1200:
    - 1.1.1.1/32
    - 12.1.0.0/16
    - 12.2.0.0/18
    - 12.12.0.0/16
  1:1300:
    - 2.2.2.2/32
    - 13.1.0.0/16
    - 13.13.0.0/16
  1:2600:
    - 3.3.3.3/32
    - 26.1.0.0/16
    - 26.26.0.0/16
